name: SmartInvs
version: 1.2.8
description: Inventory API for your Bukkit Plugins.
authors: [MinusKube, DeJayDev]
website: https://github.com/MinusKube/SmartInvs
main: fr.minuskube.inv.SmartInvsPlugin